In [7]:
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

In [2]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [3]:
x_train,x_test, y_train, y_test = train_test_split(x, y, random_state = 69)

In [4]:
clf = KNeighborsClassifier()
grid = {"n_neighbors":[3,5,7,9,11]}
abc = GridSearchCV(clf, grid)
abc.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11]})

In [5]:
abc.best_estimator_

KNeighborsClassifier(n_neighbors=3)

In [6]:
abc.cv_results_

{'mean_fit_time': array([0.00079975, 0.00040002, 0.00039463, 0.00040092, 0.00060444]),
 'std_fit_time': array([0.00116517, 0.00048992, 0.00048339, 0.00049103, 0.00049356]),
 'mean_score_time': array([0.00180039, 0.00159283, 0.00121264, 0.00119276, 0.00119553]),
 'std_score_time': array([0.00116648, 0.00048147, 0.00041015, 0.0004039 , 0.00040151]),
 'param_n_neighbors': masked_array(data=[3, 5, 7, 9, 11],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 3},
  {'n_neighbors': 5},
  {'n_neighbors': 7},
  {'n_neighbors': 9},
  {'n_neighbors': 11}],
 'split0_test_score': array([0.95652174, 0.91304348, 0.95652174, 0.95652174, 0.95652174]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 0.95652174]),
 'split2_test_score': array([1., 1., 1., 1., 1.]),
 'split3_test_score': array([0.90909091, 0.90909091, 0.90909091, 0.90909091, 0.90909091]),
 'split4_test_score': array([0.95454545, 0.95454545, 0.90909091, 0.90909091, 0.86363636]),
 'mean_test_score': array([0.96403162, 0.95533597, 0.95494071, 0.95494071, 0.93715415]),
 'std_test_score': array([0.03391848, 0.03979356, 0.04066347, 0.04066347, 0.0466738 ]),
 'rank_test_score': array([1, 2, 3, 3, 5])}

In [10]:
df = pd.DataFrame(abc.cv_results_)

In [11]:
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000800,0.001165,0.001800,0.001166,3,{'n_neighbors': 3},0.956522,1.000000,1.0,0.909091,0.954545,0.964032,0.033918,1
1,0.000400,0.000490,0.001593,0.000481,5,{'n_neighbors': 5},0.913043,1.000000,1.0,0.909091,0.954545,0.955336,0.039794,2
2,0.000395,0.000483,0.001213,0.000410,7,{'n_neighbors': 7},0.956522,1.000000,1.0,0.909091,0.909091,0.954941,0.040663,3
3,0.000401,0.000491,0.001193,0.000404,9,{'n_neighbors': 9},0.956522,1.000000,1.0,0.909091,0.909091,0.954941,0.040663,3
4,0.000604,0.000494,0.001196,0.000402,11,{'n_neighbors': 11},0.956522,0.956522,1.0,0.909091,0.863636,0.937154,0.046674,5

In [16]:
df[['param_n_neighbors','mean_test_score']]

  param_n_neighbors  mean_test_score
0                 3         0.964032
1                 5         0.955336
2                 7         0.954941
3                 9         0.954941
4                11         0.937154

In [17]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00140066, 0.00099869, 0.00080156, 0.00100889, 0.00100102,
        0.00019979]),
 'std_fit_time': array([4.91089156e-04, 2.38609238e-06, 4.00799743e-04, 9.84942904e-06,
        2.95331241e-06, 3.99589539e-04]),
 'mean_score_time': array([0.0008009 , 0.00020003, 0.00059967, 0.00059247, 0.00039964,
        0.00040007]),
 'std_score_time': array([0.00040045, 0.00040007, 0.00048964, 0.0004838 , 0.00048945,
        0.00048998]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6])}

In [18]:
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001401,0.000491,0.000801,0.000400,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000999,0.000002,0.000200,0.000400,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000802,0.000401,0.000600,0.000490,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001009,0.000010,0.000592,0.000484,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001001,0.000003,0.000400,0.000489,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000200,0.000400,0.000400,0.000490,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6

In [19]:
df[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [20]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [21]:
clf.best_score_

0.9800000000000001

In [22]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score',
 'score_samples',
 'scorer_',
 'scoring',
 'set_params',
 'transform',
 'verbose']